---
- hosts: servers
  user: elmeri
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - secrets
    - ansible-acme

  vars:
    filename: wildcard.thecodebase.tech
    zone: thecodebase.tech
    common_name: "*.thecodebase.tech"
    ssl_cert_dir: "/etc/nginx/ssl/{{ zone }}/"
    account_key: "le-account-key.pem"
    keyname: "{{ filename }}-key.pem"
    csrname: "{{ filename }}.csr"
    certname: "{{ filename }}.pem"
    fullchain: "{{ filename }}-fullchain.pem"
    # Production:
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    # Staging
    # acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory