---
# Requires ssh key under /root/.ssh/authorized_keys
- hosts: servers
  user: elmeri
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - setup
    - ansible-role-pip
    - ansible-role-nodejs
    - ansible-role-mongodb
    - ansible-role-nginx
    - ansible-mern

  vars:
    websites_user: website
    websites_home_dir: "/opt/{{ websites_user }}"
    pip_package: python3-pip
    websites:
      - main_domain: thecodebase.tech
        sub_domain: todo
        repo_https_base_url: https://github.com/thecodebasesite
        repo_name: mern
        ssl_path: /etc/nginx/ssl/thecodebase.tech
        ssl_fullchain: wildcard.thecodebase.tech-fullchain.pem
        ssl_key: wildcard.thecodebase.tech-key.pem
