---
# Requires ssh key under /root/.ssh/authorized_keys
- hosts: servers
  user: elmeri
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - setup
    - ansible-role-pip
    - ansible-role-nodejs
    - ansible-role-mongodb
    - ansible-role-nginx
    - mern

  vars:
    nodejs_npm_global_packages: [pm2, ]
    pip_package: python3-pip
    websites:
      - main_domain: thecodebase.site
        sub_domain: todo
        repo_name: mern
        ssl_path: /etc/nginx/ssl/thecodebase.site
        ssl_fullchain: thecodebase.site-fullchain.pem
        ssl_key: thecodebase.site-key.pem
