---
# Requires ssh key under /root/.ssh/authorized_keys
- hosts: servers
  user: elmeri
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - secrets
    # - setup
    # - ansible-role-pip
    - ansible-role-nginx
    # - ansible-role-mysql
    - flask

  vars:
    pip_package: python3-pip
    nginx_vhosts:
      - template: "flask.thecodebase.site.ssl.conf"
        filename: "flask.thecodebase.site.ssl.conf"
        server_name: "flask.thecodebase.site"
        state: present

      - template: "www.myhomepages.site.80.conf"
        filename: "www.myhomepages.site.80.conf"
        server_name: "myhomepages.site www.myhomepages.site"