---
# Requires ssh key under /root/.ssh/authorized_keys
- hosts: servers
  user: elmeri
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - setup
    - ansible-role-pip
    - ansible-role-nodejs
    - ansible-role-mongodb
    - ansible-role-nginx
    - mern

  vars:
    nodejs_npm_global_packages: [pm2, ]
    pip_package: python3-pip
    nginx_vhosts:
      - template: "todo.thecodebase.site.80.conf"
        filename: "todo.thecodebase.site.80.conf"
        server_name: "todo.thecodebase.site"
        state: absent
        
      - template: "todo.thecodebase.site.ssl.conf"
        filename: "todo.thecodebase.site.ssl.conf"
        server_name: "todo.thecodebase.site"
        state: present

