---

- name: "Add djano system user"
  user:
    name: "{{ django_user }}"
    comment: Django sys user
    shell: /bin/bash
    home: "{{ django_home_dir }}"


- name: "Install dependency apt packages"
  apt:
    pkg:
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-setuptools
      - python3-venv
      - libpq-dev
    state: present

- name: Install websites from github.
  git:
    repo: "https://github.com/thecodebasesite/{{ item }}.git"
    dest: "{{ django_home_dir }}/{{ item }}"
    version: master
    force: yes
    recursive: yes
  with_items:
    - django_thecodebase
  register: git_finished

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: "Install website python requirements from requirements.txt"
  pip:
    requirements: "{{ django_home_dir }}/{{ item }}/requirements.txt"
    state: forcereinstall
    virtualenv: "{{ venv_path }}"
    virtualenv_python: /usr/bin/python3.6
  with_items:
    - django_thecodebase

# - name: Init database tables
#   become_user: root
#   command: "/opt/.venv/flask/bin/python /opt/thecodebase/init_db.py {{ mysql_root_password }}"
#   register: result
#   changed_when:
#     - '"CHANGED" in result.stdout'




- name: Create logging directory for uwsgi
  file:
    path: "/var/log/uwsgi/"
    state: directory

- name: Creating a systemd Unit File for uWSGI
  template:
    src: "django-website.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  with_items:
    - django_thecodebase


- name: Enable uWSGI service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - django_thecodebase