---
- name: Install websites from github.
  become_user: "{{ django_user }}"
  git:
    repo: "https://github.com/thecodebasesite/{{ item }}.git"
    dest: "{{ django_home_dir }}/{{ item }}"
    version: master
    force: yes
    recursive: yes
  with_items:
    - django_thecodebase
  register: git_finished

- name: "Add django system user"
  user:
    name: "{{ django_user }}"
    comment: Django sys user
    shell: /bin/bash
    home: "{{ django_home_dir }}"

- name: "Install dependency apt packages"
  apt:
    pkg:
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-setuptools
      - python3-venv
      - libpq-dev
    state: present
  when: git_finished.changed


- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3
  when: git_finished.changed

- name: "Install website python requirements from requirements.txt"
  become_user: "{{ django_user }}"
  pip:
    requirements: "{{ django_home_dir }}/{{ item }}/requirements.txt"
    state: forcereinstall
    virtualenv: "{{ venv_path }}"
    virtualenv_python: /usr/bin/python3.6
  when: git_finished.changed
  with_items:
    - django_thecodebase

- name: Config file for django websites
  template:
    src: "config.json"
    dest: "{{ django_home_dir }}/{{ item }}/"
    owner: "{{ django_user }}"
    group: "{{ django_user }}"
  with_items:
    - django_thecodebase

- name: Django manage.py migrate
  become_user: "{{ django_user }}"
  command: "{{ venv_path }}/bin/python {{ django_home_dir }}/{{ item }}/manage.py migrate"
  register: result
  when: git_finished.changed
  changed_when:
    - '"No migrations to apply." not in result.stdout'
  with_items:
    - django_thecodebase

- name: Django manage.py collectstatic --noinput
  become_user: "{{ django_user }}"
  command: "{{ venv_path }}/bin/python {{ django_home_dir }}/{{ item }}/manage.py collectstatic --noinput"
  register: collectstatic_result
  when: git_finished.changed
  changed_when:
    - 'collectstatic_result.stdout_lines[-1].startswith("0 static files copied") == False or "unmodified" not in collectstatic_result.stdout'
  with_items:
    - django_thecodebase

- name: Django manage.py check --deploy (Check that security settings are OK)
  become_user: "{{ django_user }}"
  command: "{{ venv_path }}/bin/python {{ django_home_dir }}/{{ item }}/manage.py check --deploy"
  register: result
  when: git_finished.changed
  failed_when:
    - '"System check identified no issues (0 silenced)." not in result.stdout'
  changed_when:
    - 'False == True'
  with_items:
    - django_thecodebase

- name: Create logging directory for uwsgi
  become_user: "{{ django_user }}"
  file:
    path: "/var/log/uwsgi/"
    state: directory

- name: Creating a systemd Unit File for uWSGI
  template:
    src: "django-website.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_result
  with_items:
    - django_thecodebase


- name: Enable uWSGI service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  when: git_finished.changed or systemd_result.changed
  with_items:
    - django_thecodebase