---

- name: Update all packages to the latest version
  apt:
    name: aptitude 

- name: Update and upgrade apt packages
  tags: setup
  become: true
  apt:
    upgrade: dist
    state: latest
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Enable SSH service
  service:
    name: ssh
    enabled: yes
    state: started

- name: Make sure no suspend when lid is closed
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandleLidSwitch=ignore'
    line: 'HandleLidSwitch=ignore'
    insertafter: "#HandleLidSwitch=suspend"
  register: logind
  

- name: Restart systemd-logind service
  service:
    name: systemd-logind
    enabled: yes
    state: restarted
  when: logind.changed

- name: Define login_user
  set_fact:
    login_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: login_user is not defined
