---

# Example git checkout from Ansible Playbooks
- name: Install websites from github.
  git:
    repo: 'https://github.com/thecodebasesite/{{ item }}.git'
    dest: /opt/{{ item }}
    version: master
    force: yes
  with_items:
    - mern
    - thecodebase
  register: git_finished

- name: Install packages based on package.json.
  npm:
    path: /opt/mern/{{ item }}
  with_items:
    - backend
    - frontend
  register: npm_finished
  when: git_finished.changed

- name: Define nodejs_install_npm_user
  set_fact:
    nodejs_install_npm_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: nodejs_install_npm_user is not defined


- name: Stop Mern Apps
  become_user: "{{ nodejs_install_npm_user }}"
  command: "{{ npm_config_prefix }}/bin/pm2 stop {{ item }} chdir=/opt/mern/{{ item }}"
  ignore_errors: yes
  with_items:
    - backend

- name: Start Mern Apps
  become_user: "{{ nodejs_install_npm_user }}"
  command: "{{ npm_config_prefix }}/bin/pm2 start --name={{ item }} /usr/bin/npm -- start chdir=/opt/mern/{{ item }}"
  ignore_errors: yes
  with_items:
    - backend

- name: Configures a startup script to launch PM2 and its managed processes on server boots
  command: "{{ npm_config_prefix }}/bin/pm2 startup systemd"
